name: Build Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: |
          ls -la
          docker build . -f Dockerfile -t 0o00/demo-image-test:latest
      
      - name: Push the Docker image
        run: docker push 0o00/demo-image-test:latest
